--Ejercicios avanzados de procedimientos y triggers

--Ejercicio 1

--Crea un procedimiento actualizar_precios_por_categoria 
--que reciba un porcentaje de aumento (parámetro IN) y aplique el aumento solo 
--a productos cuyo precio promedio por pedido (calculado con una función) sea mayor a 500. 
--Usa un cursor para iterar sobre los productos.

CREATE OR REPLACE PROCEDURE actualizar_precios_por_categoria(p_aumento IN NUMBER) IS
    CURSOR cur_productos IS
        SELECT ProductoID, Precio
        FROM Productos
        WHERE (SELECT AVG(Precio) FROM DetallesPedidos WHERE ProductoID = Productos.ProductoID) > 500;
BEGIN
    FOR producto IN cur_productos LOOP
        UPDATE Productos
        SET Precio = Precio + (Precio * p_aumento / 100)
        WHERE ProductoID = producto.ProductoID;
    END LOOP;
END;
/
-- Crea un trigger que registre en una tabla de auditoría cada vez que se actualice el precio de un producto.
CREATE TABLE AuditoriaPrecios (
    AuditoriaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductoID NUMBER,
    PrecioAnterior NUMBER,
    PrecioNuevo NUMBER,
    FechaActualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE OR REPLACE TRIGGER trg_auditoria_precios
AFTER UPDATE OF Precio ON Productos
FOR EACH ROW
BEGIN
    INSERT INTO AuditoriaPrecios (ProductoID, PrecioAnterior, PrecioNuevo)
    VALUES (:OLD.ProductoID, :OLD.Precio, :NEW.Precio);
END;
/

--Ejercicio 2
--Crea un trigger auditar_eliminacion_pedido que se dispare después de eliminar un pedido 
--y registre el PedidoID, ClienteID, Total y la fecha de eliminación 
--en una tabla de auditoría AuditoriaPedidos.

CREATE TABLE AuditoriaPedidos (
    AuditoriaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PedidoID NUMBER,
    ClienteID NUMBER,
    Total NUMBER,
    FechaEliminacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE OR REPLACE TRIGGER auditar_eliminacion_pedido
AFTER DELETE ON Pedidos
FOR EACH ROW
BEGIN
    INSERT INTO AuditoriaPedidos (PedidoID, ClienteID, Total)
    VALUES (:OLD.PedidoID, :OLD.ClienteID, (SELECT SUM(Precio * Cantidad) FROM DetallesPedidos WHERE PedidoID = :OLD.PedidoID));
END;
/
